### ISSUE TITLE
AI标注失败

### ISSUE THREAD

**Issue by hitbuyi** [xtreme1-io/xtreme1#328]
AI标注失败，为什么？
```
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO load_params_from_file: ==> Loading parameters from checkpoint ../cbgs_voxel0075_centerpoint_nds_6648.pth to GPU
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO load_params_from_file: ==> Done (loaded 558/558)
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO process_data: ---------- http://minio:9000/xtreme1/2/3/5987340b9a3c423f86e4b71646a2f93d/lidar_point_cloud_0/binary-2.pcd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20250629%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250629T100154Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=04f8cf7cfd2ee35d023cb1556b1457839a80deec85d811e6313edbb41e6e3236 ----------
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_interval: DOWNLOAD pcd(1.9MB):      0.012s
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_interval: LOAD pcd:                 0.0014s
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_interval: VALIDATE points:          0.0089s
point-cloud-object-detection-1  | 2025-06-29 10:01:59 ERROR process_data: CUDA error: no kernel image is available for execution on the device
point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
point-cloud-object-detection-1  | Traceback (most recent call last):
point-cloud-object-detection-1  |   File "app.py", line 80, in process_data
point-cloud-object-detection-1  |     results, _ = self.predictor(points=pc, full_nms=True)
point-cloud-object-detection-1  |   File "/app/pcdet_open/src/predictor.py", line 80, in __call__
point-cloud-object-detection-1  |     pred_dicts, _ = self.model.forward(data_dict)
point-cloud-object-detection-1  |   File "/src/pcdet/models/detectors/centerpoint.py", line 11, in forward
point-cloud-object-detection-1  |     batch_dict = cur_module(batch_dict)
point-cloud-object-detection-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
point-cloud-object-detection-1  |     return forward_call(*input, **kwargs)
point-cloud-object-detection-1  |   File "/src/pcdet/models/backbones_3d/vfe/mean_vfe.py", line 26, in forward
point-cloud-object-detection-1  |     points_mean = voxel_features[:, :, :].sum(dim=1, keepdim=False)
point-cloud-object-detection-1  | RuntimeError: CUDA error: no kernel image is available for execution on the device
point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_request: 200 POST /pointCloud/recognition (172.18.0.10) 5109.50ms
```

**Comment by hitbuyi** [comment]
> AI标注失败，为什么？我的环境是 ubuntu20.04 + CUDA11.8,RTX3060
> 
> ```
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO load_params_from_file: ==> Loading parameters from checkpoint ../cbgs_voxel0075_centerpoint_nds_6648.pth to GPU
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO load_params_from_file: ==> Done (loaded 558/558)
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO process_data: ---------- http://minio:9000/xtreme1/2/3/5987340b9a3c423f86e4b71646a2f93d/lidar_point_cloud_0/binary-2.pcd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20250629%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250629T100154Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=04f8cf7cfd2ee35d023cb1556b1457839a80deec85d811e6313edbb41e6e3236 ----------
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_interval: DOWNLOAD pcd(1.9MB):      0.012s
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_interval: LOAD pcd:                 0.0014s
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_interval: VALIDATE points:          0.0089s
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 ERROR process_data: CUDA error: no kernel image is available for execution on the device
> point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> point-cloud-object-detection-1  | Traceback (most recent call last):
> point-cloud-object-detection-1  |   File "app.py", line 80, in process_data
> point-cloud-object-detection-1  |     results, _ = self.predictor(points=pc, full_nms=True)
> point-cloud-object-detection-1  |   File "/app/pcdet_open/src/predictor.py", line 80, in __call__
> point-cloud-object-detection-1  |     pred_dicts, _ = self.model.forward(data_dict)
> point-cloud-object-detection-1  |   File "/src/pcdet/models/detectors/centerpoint.py", line 11, in forward
> point-cloud-object-detection-1  |     batch_dict = cur_module(batch_dict)
> point-cloud-object-detection-1  |   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
> point-cloud-object-detection-1  |     return forward_call(*input, **kwargs)
> point-cloud-object-detection-1  |   File "/src/pcdet/models/backbones_3d/vfe/mean_vfe.py", line 26, in forward
> point-cloud-object-detection-1  |     points_mean = voxel_features[:, :, :].sum(dim=1, keepdim=False)
> point-cloud-object-detection-1  | RuntimeError: CUDA error: no kernel image is available for execution on the device
> point-cloud-object-detection-1  | CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> point-cloud-object-detection-1  | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> point-cloud-object-detection-1  | 2025-06-29 10:01:59 INFO log_request: 200 POST /pointCloud/recognition (172.18.0.10) 5109.50ms
> ```

查了一下原来模型的构建环境：

```
tbuyi-Dell-G15-5511:/media/hitbuyi/Crucial_X61/labeling/xtreme1/xtreme1-v0.9.1$ docker inspect basicai/xtreme1-point-cloud-object-detection
[
    {
        "Id": "sha256:f4ced7338074cbe82c4b94b84a5ff115fb2abc9b5f4409ea721287ea20115b90",
        "RepoTags": [
            "basicai/xtreme1-point-cloud-object-detection:latest"
        ],
        "RepoDigests": [
            "basicai/xtreme1-point-cloud-object-detection@sha256:5141978e964f73f401c0118a111ee0ecc09d27dcd2b3603afeab93123bce80fe"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2023-03-16T03:55:59.426383935Z",
        "DockerVersion": "20.10.16",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NVARCH=x86_64",
                "NVIDIA_REQUIRE_CUDA=cuda>=10.2 brand=tesla,driver>=418,driver<419",
                "NV_CUDA_CUDART_VERSION=10.2.89-1",
                "CUDA_VERSION=10.2.89",
                "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
                "NV_CUDA_LIB_VERSION=10.2.89-1",
                "NV_NVTX_VERSION=10.2.89-1",
                "NV_LIBNPP_VERSION=10.2.89-1",
                "NV_LIBCUSPARSE_VERSION=10.2.89-1",
                "NV_LIBCUBLAS_PACKAGE_NAME=libcublas10",
                "NV_LIBCUBLAS_VERSION=10.2.2.89-1",
                "NV_LIBCUBLAS_PACKAGE=libcublas10=10.2.2.89-1",
                "NV_LIBNCCL_PACKAGE_NAME=libnccl2",
                "NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1",
                "NCCL_VERSION=2.13.4-1",
                "NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda10.2",
                "NV_CUDA_CUDART_DEV_VERSION=10.2.89-1",
                "NV_NVML_DEV_VERSION=10.2.89-1",
                "NV_LIBCUSPARSE_DEV_VERSION=10.2.89-1",
                "NV_LIBNPP_DEV_VERSION=10.2.89-1",
                "NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev",
                "NV_LIBCUBLAS_DEV_VERSION=10.2.2.89-1",
                "NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev=10.2.2.89-1",
                "NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev",
                "NV_LIBNCCL_DEV_VERSION=2.13.4-1",
                "NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.13.4-1+cuda10.2",
                "LIBRARY_PATH=/usr/local/cuda/lib64/stubs",
                "NV_CUDNN_PACKAGE_VERSION=8.5.0.96-1",
                "NV_CUDNN_VERSION=8.5.0.96",
                "NV_CUDNN_PACKAGE_NAME=libcudnn8",
                "NV_CUDNN_PACKAGE=libcudnn8=8.5.0.96-1+cuda10.2",
                "NV_CUDNN_PACKAGE_DEV=libcudnn8-dev=8.5.0.96-1+cuda10.2",
                "CUDNN_VERSION=8.5.0.96",
                "DEBIAN_FRONTEND=noninteractive",
                "TORCH_CUDA_ARCH_LIST=5.0 5.2 6.0 6.1 7.0 7.5+PTX"
            ],
            "Cmd": null,
            "Image": "sha256:f7c81e604b577d2dc081bb36e8058f41826b35fe71657b7748c26a181bc4046f",
            "Volumes": null,
            "WorkingDir": "/app/pcdet_open",
            "Entrypoint": [
                "python",
                "app.py",
                "../cbgs_voxel0075_centerpoint_nds_6648.pth"
            ],
            "OnBuild": null,
            "Labels": {
                "com.nvidia.cudnn.version": "8.5.0.96",
                "maintainer": "NVIDIA CORPORATION <cudatools@nvidia.com>"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 8504421360,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/40b0b1842ef4de578c3b5e3518f2bf29fc4f0832d63570bb8a581f28c120d3a9/diff:/var/lib/docker/overlay2/3a412a162354d20e3bb24aee0d20a651d8e88026c4384a7d43e6c58e66ccee08/diff:/var/lib/docker/overlay2/6f9534ae1d901b052efa7eaf97043677d196d3e4ae9af6a7ecad362e20571e8e/diff:/var/lib/docker/overlay2/a197f0204bc035e21f21a04278b430be2208bb6d98a4c604b657683a0fbd23eb/diff:/var/lib/docker/overlay2/7a134ddb6683c1d285d6433c6520bfac6a4dda135f3b68e8a5cb8e1bf8f7369e/diff:/var/lib/docker/overlay2/90ff20debde35779f099ecd90d25e79521d23fbafea69a6c03851308918456db/diff:/var/lib/docker/overlay2/e43853a81369ef8d7c58c8cc1c897ca4cc83af0d31010df9721b96a32b345fd9/diff:/var/lib/docker/overlay2/232fc1775685bcd4753755793e063c933a48cfa123ed261eec8f8279641c2ec7/diff:/var/lib/docker/overlay2/4292714acb7544301f5e9ca3d062f9f1af1de4e3c4ae8723f13f74b61376e0a0/diff:/var/lib/docker/overlay2/787a625bb256deca07be1405f42eb69fcac9fcda749c55e8a386b583ec24c124/diff:/var/lib/docker/overlay2/4fd3a4df5baf4c41a5d2f8f15666be11f093795635fbeee721721f3fc76511ab/diff:/var/lib/docker/overlay2/3d8e2684649d5d6c1d0651d48449338046d9c84396f935831f04091066961718/diff:/var/lib/docker/overlay2/fb8247689febf6cd54072996736fccb9883bcfd168097eef503abb9eda4266bd/diff:/var/lib/docker/overlay2/8b603acc54d5f6e6bfc01e6d821921e2061982f24be4c93aba55806f3e3fcc5e/diff:/var/lib/docker/overlay2/4c95187d9e44d6510d5776008f170f703446f15f21ae5a7fb1197e93ce0f64e9/diff:/var/lib/docker/overlay2/12375fb32864bd5249144c87682c30efd744538ee62bfd3c39f7c1b0acb868f8/diff:/var/lib/docker/overlay2/94cf2376d1f52d5dc1c4828e539214493af51ac9f4ae2445cfd57b2472c60f00/diff:/var/lib/docker/overlay2/34fa3dd669a1b90ac78b7bd7237a1eb5ccc984048554852a0a6fd628f8df40ac/diff:/var/lib/docker/overlay2/29514ec78bf167e2c083df007880e105ef6166d47c44285db7d93785832f0be6/diff:/var/lib/docker/overlay2/619b1530b15bc7deed31e41ec39d27429694524e2d0f65d2179663c4893cfd52/diff:/var/lib/docker/overlay2/1f6c8a280a31b71baee41f1c5bcb2dfdc2e923357eaf106aaa9f36a86fd8db8b/diff:/var/lib/docker/overlay2/9a6fbf0b388161af8506958f528ed451a399de184347b5d1c353909eb4ca79fd/diff",
                "MergedDir": "/var/lib/docker/overlay2/d00cdbf5df255a56de7380b6cd0b0747aaaff737beaabafce76412f36685912e/merged",
                "UpperDir": "/var/lib/docker/overlay2/d00cdbf5df255a56de7380b6cd0b0747aaaff737beaabafce76412f36685912e/diff",
                "WorkDir": "/var/lib/docker/overlay2/d00cdbf5df255a56de7380b6cd0b0747aaaff737beaabafce76412f36685912e/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:4a641e21953d4161b38a01933802b61ad314880fc6a93e8667dd210846fe7071",
                "sha256:47fed71b96b61739ea7c1de86e6a00f7a325c8c858c2279fbec1d6143d466d13",
                "sha256:c3d5f599cf43dfdbdb305b091f17de853d1f1df5b6169bd43077f01bdbf568b0",
                "sha256:759973ca137f92ec9a3798c4d720a8a2af2e7f4b1601a77c8c4ebcc96e81333e",
                "sha256:c22d95ca8e81985c6579e3ccc64335cfd71c5a642b42cb31af88c2dc8748f02e",
                "sha256:4fba36379304e103b427e2631e0b1a062d67ddf75c298ac9802ac475810c4b1b",
                "sha256:53cce66f478bac058127ef7775b7e4c32f482aa532977ef8e7aa1731edb75496",
                "sha256:da9ae064ef6968bcda9c803f92ca80304ade1a3398f8847ea04a62bff8529531",
                "sha256:8e663c5c86c828ae6f0c4ad909a2fa6b6850652ba12b7892b5da75d4d68a8f7f",
                "sha256:4d7729d0b89a7804a0113076d9283ddf48142627a02e3fc9d4447de0c8b20d50",
                "sha256:e6c07c7dc36bc5aa04fded67820ee3068d58ebc44714d4a3ec7012dbf9969409",
                "sha256:29ff877690051e622fb76e0ca2993f9658abf853c1a8ffca02e69f38689ced45",
                "sha256:f17368583667792fb893491e3e311bcd23e5b42dbb2193c1e4bb092750d8b93e",
                "sha256:0b372cb7cf771ae777598a34b1326772c605c2d4720b1002f8e97ecd88e5c63d",
                "sha256:35ae0fb09094e978686684ae0b814a04e52a934816985e31497da9eca6c51acc",
                "sha256:d67c44054237cc92898237c2a6d56473c9822edb9500372b4ccf7e85569b695d",
                "sha256:dd9354900a4c09baf56e57f59fdb3303524e3da3aee226f299ba59da9c0a89c6",
                "sha256:c1078fabd7cb8480b9597a7bab0aba3b4d448c0b7a9f994260bae87e16af93ea",
                "sha256:4821cb5f77a84a338bd76a0b771ded89d6776fa2f0daccd0f1a85633fa62ef29",
                "sha256:0b97e60c69996cd1ca1775387be4c7f3a15a3d0fddd34d9da3abce1f3c614a96",
                "sha256:303a76b08d1d9839b032b1ab6d80b65ed8851682484e4fff068a30fe481ae64e",
                "sha256:5f5eb16825338beb15d5011fce605a21d0bb6751aba37b709e954a8f73b6d0be",
                "sha256:2eb3954a6df9d41ce973006091b619de820a9db56e8d645d7bbb6906291e39c3"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

```


原来的模型是cuda10.2环境构建的，只支持到算力范围为：5.0 5.2 6.0 6.1 7.0 7.5+PTX，能不能更新一下？

**Comment by Mujin-z** [comment]
> 已经解决，参考[这里](https://github.com/hitbuyi/xtreme1)

感谢 @hitbuyi

**Comment by SakuraTau** [comment]
> > 已经解决，参考[这里](https://github.com/hitbuyi/xtreme1)
> 
> 感谢 [@hitbuyi](https://github.com/hitbuyi)
Hello, I've encountered the same issue. Would you be open to discussing it?

**Comment by hitbuyi** [comment]
> > > 已经解决，参考[这里](https://github.com/hitbuyi/xtreme1)
> > 
> > 
> > 感谢 [@hitbuyi](https://github.com/hitbuyi)
> > Hello, I've encountered the same issue. Would you be open to discussing it?

This issue is open now

**Comment by jotamotk** [comment]
你好，感谢排查。结论和你判断一致：官方预置的点云模型镜像 `basicai/xtreme1-point-cloud-object-detection` 基于 CUDA 10.2 构建（PyTorch 1.10.1+cu102、spconv-cu102，自定义算子编译算力为 5.0–7.5），不支持 RTX 30 系（算力 8.6）和 40 系（8.9）等更新架构的显卡，所以文件下载都正常，但推理时报 `no kernel image is available`。这是预置镜像的兼容性限制，与后端配置无关。目前已发布的镜像没有更新，README 中写的参考 GPU 是 T4（算力 7.5）。

如需在新显卡上使用，可以基于 https://github.com/xtreme1-io/point-cloud-object-detection 自行构建（以下思路官方尚未验证，依赖可能需要调整）：

1. 修改 `base_image/Dockerfile`：基础镜像换成支持你显卡的 CUDA 版本（30 系需 CUDA ≥ 11.1，40 系建议 ≥ 11.8），同步替换 torch / spconv 的 CUDA 版本，并在 `TORCH_CUDA_ARCH_LIST` 中加入 `8.6`（40 系再加 `8.9`）。
2. 构建：

   ```bash
   docker build -t my/pcod-base:cu118 base_image
   # 把 Dockerfile 的 FROM 改为 my/pcod-base:cu118（构建时会从 S3 下载模型权重）
   docker build -t my/xtreme1-point-cloud-object-detection:cu118 .
   ```

3. 在 `docker-compose.yml` 的 `point-cloud-object-detection` 服务中把 `image` 改为上面的 tag，并把 `pull_policy: always` 改为 `never`（否则 `docker compose up` 会从 Docker Hub 重新拉官方镜像覆盖）。
4. `docker compose --profile model up -d`。

社区同学 @hitbuyi 分享了自行升级的版本，可以参考，但官方未审阅。
